services:
  web:
    build: .
    container_name: docker-demo-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
  db:
    image: postgres:13-alpine
    container_name: docker-demo-db
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: demoapp
      POSTGRES_USER: demouser
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: docker-demo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
